### ISSUE TITLE
contributing problem

### ISSUE THREAD

**Issue by sourabh1031** [danthareja/contribute-to-open-source#49]
i encountered errors when i ran your code in all the lines 
![2017-12-15 1](https://user-images.githubusercontent.com/25590627/34048808-0c473de6-e1db-11e7-800f-7e879aff18b4.png)

**Comment by danthareja** [comment]
In order to reduce distractions from the exercise, please open your issue in the partner repo:

https://github.com/danthareja/contribute-to-open-source-server/issues/new

I'll be happy to chat with you there, @sourabh1031!
